name: nest_loop_mobile
description: "Mobile app for NestLoop"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  modal_bottom_sheet: ^3.0.0
  pinput: ^5.0.1
  intl: ^0.18.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  open_file: ^3.5.10
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.0+1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/png/
    - assets/svg/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/satoshi/Satoshi-Black.otf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_24pt-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
